# Generated by Django 4.2.23 on 2025-09-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='person_image/')),
                ('short_biography', models.TextField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('quote', models.CharField(blank=True, max_length=320)),
            ],
        ),
        migrations.RemoveField(
            model_name='street',
            name='description',
        ),
        migrations.AddField(
            model_name='street',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.person'),
        ),
    ]
