# Generated by Django 4.2.23 on 2025-11-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_remove_street_description_street_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('military', 'Військова справа'), ('politics', 'Політика'), ('science', 'Наука'), ('business', 'Бізнес'), ('culture', 'Культура'), ('writers', 'Письменницька діяльність'), ('sport', 'Спорт'), ('public', 'Громадська діяльність'), ('religion', 'Релігія'), ('other', 'Інше')], default='other', max_length=30),
            preserve_default=False,
        ),
    ]
